#Hard disable entire modules. Use at your own risk and don't ask for support if you use this
#Fri Jun 13 22:48:18 CEST 2025
decorative_blocks=true
another_furniture=true
friendsandfoes=true
chipped=true
