#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed May 22 22:20:30 CEST 2024
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
maxShadowRenderDistance=6
shaderPack=
enableShaders=true
